SELECT vendor_id,
       pickup_date,
       pickup_datetime,
       dropoff_date,
       dropoff_datetime,
       passenger_count,
       trip_distance,
       pickup_longitude,
       pickup_latitude,
       rate_code,
       store_and_fwd_flag,
       dropoff_longitude,
       dropoff_latitude,
       payment_type,
       fare_amount,
       surcharge,
       mta_tax,
       tip_amount,
       tolls_amount,
       total_amount
FROM   {{ source('samples', 'NYC-taxi-trips-iceberg')}}