SELECT vendor_id,
       cast(pickup_datetime as date) as pickup_date,
       pickup_datetime,
       cast(dropoff_datetime as date) as dropoff_date,
       dropoff_datetime,
       passenger_count,
       trip_distance,
       pickup_longitude,
       pickup_latitude,
       rate_code,
       store_and_fwd_flag,
       dropoff_longitude,
       dropoff_latitude,
       payment_type,
       fare_amount,
       surcharge,
       mta_tax,
       tip_amount,
       tolls_amount,
       total_amount
FROM   {{ source('nyc', 'sample_data')}}